Update dotnet-desktop.yml

diff --git a/.github/workflows/dotnet-desktop.yml b/.github/workflows/dotnet-desktop.yml
--- a/.github/workflows/dotnet-desktop.yml
+++ b/.github/workflows/dotnet-desktop.yml
@@ -109,19 +109,20 @@ jobs:
       
           # Format the output
           echo "### SonarQube Analysis Summary 🚀" >> $GITHUB_STEP_SUMMARY 
-          echo "🔹 **Quality Gate Status:** $([[ $STATUS == "OK" ]] && echo '✅ Passed' || echo '🔴 Failed')"
-          echo "✅ **Bugs:** $BUGS"
-          echo "🔴 **Code Smells:** $CODE_SMELLS"
-          echo "🟡 **Coverage:** $COVERAGE%"
+          echo "" >> $GITHUB_STEP_SUMMARY
+          echo "🔹 **Quality Gate Status:** $([[ $STATUS == "OK" ]] && echo '✅ Passed' || echo '🔴 Failed')"  >> $GITHUB_STEP_SUMMARY
+          echo "✅ **Bugs:** $BUGS" >> $GITHUB_STEP_SUMMARY
+          echo "🔴 **Code Smells:** $CODE_SMELLS" >> $GITHUB_STEP_SUMMARY
+          echo "🟡 **Coverage:** $COVERAGE%" >> $GITHUB_STEP_SUMMARY
           
           if [[ "${{ github.event_name }}" == "pull_request" ]]; then
             PR_ID=${{ github.event.pull_request.number }}
             SONARQUBE_URL="https://sonarcloud.io/dashboard?id=$project_key&pullRequest=$PR_ID"
-            echo "🔗 **SonarQube PR Dashboard:** [View PR Analysis]($SONARQUBE_URL)"
+            echo "🔗 **SonarQube PR Dashboard:** [View PR Analysis]($SONARQUBE_URL)" >> $GITHUB_STEP_SUMMARY
           else
             BRANCH_NAME=${{ github.ref_name }}
             SONARQUBE_URL="https://sonarcloud.io/dashboard?id=$project_key&branch=$BRANCH_NAME"
-            echo "🔗 **SonarQube Branch Dashboard:** [View Branch Analysis]($SONARQUBE_URL)"
+            echo "🔗 **SonarQube Branch Dashboard:** [View Branch Analysis]($SONARQUBE_URL)" >> $GITHUB_STEP_SUMMARY
           fi       
 
       - name: Upload Build Artifacts (Optional)
